services:
  - type: web
    name: military-asset-management
    runtime: docker
    plan: free
    repo: https://github.com/harint369/military-asset-management.git
    branch: main
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: REQUIRED